# version: "3"
# services:
#   zookeeper:
#     image: 'bitnami/zookeeper:latest'
#     ports:
#       - '2181:2181'
#     environment:
#       - ALLOW_ANONYMOUS_LOGIN=yes
#   kafka:
#     image: 'bitnami/kafka:latest'
#     container_name: 'kafka'
#     ports:
#       - '9092:9092'
#     environment:
#       - KAFKA_BROKER_ID=1
#       - KAFKA_LISTENERS=PLAINTEXT://:9092
#       - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
#       - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
#       - ALLOW_PLAINTEXT_LISTENER=yes
#     depends_on:
#       - zookeeper

#   kafka2:
#     image: 'bitnami/kafka:latest'
#     container_name: 'kafka2'
#     ports:
#       - '9095:9095'
#     environment:
#       - KAFKA_BROKER_ID=2
#       - KAFKA_LISTENERS=PLAINTEXT://:9095
#       - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9095
#       - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
#       - ALLOW_PLAINTEXT_LISTENER=yes
#     depends_on:
#       - zookeeper


# version: '3'
# services:
#   magic:
#     image: "digitsy/kafka-magic"
#     ports:
#       - "8080:80"
#     volumes:
#       - .:/config
#     environment:
#       KMAGIC_ALLOW_TOPIC_DELETE: "true"
#       KMAGIC_CONFIG_STORE_TYPE: "file"
#       KMAGIC_CONFIG_STORE_CONNECTION: "Data Source=/config/KafkaMagicConfig.db;"
#       KMAGIC_CONFIG_ENCRYPTION_KEY: "ENTER_YOUR_KEY_HERE"

version: '2'
services:
  kafka:
    image: landoop/fast-data-dev
    ports:
      - "2181:2181"
      - "3030:3030"
      - "3031:3031"
      - "9092:9092"
      - "8081:8081"
      - "8082:8082"
      - "8083:8083"
    environment:
      ADV_HOST: kafka

      
  magic:
    image: digitsy/kafka-magic
    ports:
      - "8080:80"
    environment:
      KMAGIC_ALLOW_TOPIC_DELETE: "true"